/// Flutter icons Measure
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Measure
///      fonts:
///       - asset: fonts/Measure.ttf
///
/// 
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class Measure {
  Measure._();

  static const _kFontFam = 'Measure';
  static const String? _kFontPkg = null;

  static const IconData ruler = IconData(0xf044, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
